services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 8090
      APP_CORS_ALLOWED_ORIGINS: "*"
    ports:
      - "8090:8090"
    volumes:
      - ./data:/app/data
